# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
