# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170808_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
